language: python
python:
  - 2.7

###
### Add services
###
services:
  - docker


###
### Global variables
###
env:
  global:
    - MY_DOCKER_NAME="arithorn-bind-docker"


###
### Install
###
install:

  # Create overview section script
  - echo "#!/bin/sh" > /tmp/section.sh
  - echo " echo '===================================================================================================='" >> /tmp/section.sh
  - echo " echo '===================================================================================================='" >> /tmp/section.sh
  - echo " echo \"= \${1}\"" >> /tmp/section.sh
  - echo " echo '===================================================================================================='" >> /tmp/section.sh
  - echo " echo '===================================================================================================='" >> /tmp/section.sh
  - chmod +x /tmp/section.sh


  # Show Docker version
  - docker version

  # Build my docker
  - docker build -t peetg/${MY_DOCKER_NAME} .


###
### Test
###
script:

  ################################################################################
  ## 01.) [a](DEBUG) Test plain docker
  ################################################################################
  - /tmp/section.sh "01.) [a](DEBUG) Test plain docker"
  - docker run
      -e DEBUG_COMPOSE_ENTRYPOINT=1
      --name ${MY_DOCKER_NAME} peetg/${MY_DOCKER_NAME} &
  - sleep 5
  - docker ps
  - docker exec ${MY_DOCKER_NAME} named -V
  - docker exec ${MY_DOCKER_NAME} named -V | grep -oiE '^BIND[[:space:]]+[0-9.]+'
  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}"

  - /tmp/section.sh "01.) [a](DEBUG) Test plain docker"
  - docker run
      -e DEBUG_COMPOSE_ENTRYPOINT=0
      --name ${MY_DOCKER_NAME} peetg/${MY_DOCKER_NAME} &
  - sleep 5
  - docker ps
  - docker exec ${MY_DOCKER_NAME} named -V
  - docker exec ${MY_DOCKER_NAME} named -V | grep -oiE '^BIND[[:space:]]+[0-9.]+'
  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}"
